sudo: required
dist: trusty
services:
  - docker
before_install:
- docker pull lineageos4microg/docker-lineage-cicd
- git clone git://github.com/RR-msm7x30/android_device_samsung_ancora.git -b cm-12.1 device/samsung/ancora



- docker run -e "BRANCH_NAME=cm-12.1" -e "DEVICE_LIST=ancora" -v "/home/user/lineage:/srv/src" -v "/home/user/zips:/srv/zips" -v "/home/user/logs:/srv/logs" -v "/home/user/cache:/srv/ccache" -v "$(pwd):/srv/local_manifests" lineageos4microg/docker-lineage-cicd
language: None
cache: ccache
env: GCC_VERSION=7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - flex
script:
# Install dependency
- sudo apt-get install -y dpkg
- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic main"
#- wget http://ftp.br.debian.org/debian/pool/main/f/flex/libfl2_2.6.4-6.1_amd64.deb
#- sudo dpkg -i libfl2_2.6.4-6.1_amd64.deb
#- sudo add-apt-repository ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt install libfl2
# getting UberTC
- git clone  --depth=1 "https://bitbucket.org/matthewdalex/arm-eabi-7.x" "../arm-eabi-7.x"
- export CROSS_COMPILE="$(pwd)/../arm-eabi-7.x/bin/arm-eabi-"
- sudo ldconfig
#- source build.sh <<< "${nbasebuildsh}"
- export ARCH=arm && export SUBARCH=arm
- make clean && make mrproper 
#- make ancora_oc_exuv_defconfig 
#- make -j 4 V=1


# Export of zipfile to deploy
#- export zipfile="${zipfile}"

deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${KEY}
  file_glob: true
  file: "arch/${ARCH}/boot/*Image*"
  on:
  #  tags: true
    all_branches: true

